
	<footer>
	   <script type="text/javascript" src="<?php echo $_layoutParams["route_js"]?>/jquery.min.js"></script>
	    <script type="text/javascript" src="<?php echo $_layoutParams["route_bootstrap_js"]?>/bootstrap.min.js"></script>
	    <script type="text/javascript" src="<?php echo $_layoutParams["route_js"]?>/jquery.backstretch.min.js"></script>
	    <script type="text/javascript" src="<?php echo $_layoutParams["route_js"]?>/scripts.js"></script>
	   
	</footer>
</body>
</html>