<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Inicio de Sesion</title>

	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--Agregamos la libreria que se encuentra en la carpeta bootstrap-->
	<link rel="stylesheet" type="text/css" href="<?php echo $_layoutParams["route_bootstrap_css"]?>/bootstrap.css">
	<link rel="stylesheet" type="text/css" href="<?php echo $_layoutParams["route_bootstrap_css"]?>/bootstrap-responsive.css">
	<link rel="stylesheet" type="text/css" href="<?php echo $_layoutParams["route_css"]?>/style.css">
</head>
<body>
	
	